name: neuro4ml
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - matplotlib
  - seaborn
  - scipy
  - jupyter
  - notebook
  - ipykernel
  - ipywidgets
  - ipympl
  - pytorch
  - cpuonly
  - pip
  - pip:
    - brian2
    - snntorch
    - omegaconf